vscode --install-extension abusaidm.html-snippets
vscode --install-extension almenon.arepl
vscode --install-extension atlassian.atlascode
vscode --install-extension dongli.python-preview
vscode --install-extension donjayamanne.githistory
vscode --install-extension eamodio.gitlens
vscode --install-extension ecmel.vscode-html-css
vscode --install-extension esbenp.prettier-vscode
vscode --install-extension frhtylcn.pythonsnippets
vscode --install-extension hbenl.vscode-test-explorer
vscode --install-extension HookyQR.beautify
vscode --install-extension littlefoxteam.vscode-python-test-adapter
vscode --install-extension ms-azuretools.vscode-docker
vscode --install-extension ms-python.python
vscode --install-extension ms-python.vscode-pylance
vscode --install-extension ms-toolsai.jupyter
vscode --install-extension ms-toolsai.jupyter-keymap
vscode --install-extension ms-toolsai.jupyter-renderers
vscode --install-extension ms-vscode-remote.remote-containers
vscode --install-extension ms-vscode-remote.remote-ssh
vscode --install-extension ms-vscode-remote.remote-ssh-edit
vscode --install-extension ms-vscode-remote.remote-wsl
vscode --install-extension ms-vscode-remote.vscode-remote-extensionpack
vscode --install-extension ms-vscode.test-adapter-converter
vscode --install-extension mwpb.java-prettier-formatter
vscode --install-extension njpwerner.autodocstring
vscode --install-extension njqdev.vscode-python-typehint
vscode --install-extension pflannery.vscode-versionlens
vscode --install-extension pthorsson.vscode-jsp
vscode --install-extension redhat.java
vscode --install-extension redhat.vscode-yaml
vscode --install-extension sohibe.java-generate-setters-getters
vscode --install-extension SonarSource.sonarlint-vscode
vscode --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
vscode --install-extension VisualStudioExptTeam.vscodeintellicode
vscode --install-extension vscjava.vscode-java-debug
vscode --install-extension vscjava.vscode-java-dependency
vscode --install-extension vscjava.vscode-java-pack
vscode --install-extension vscjava.vscode-java-test
vscode --install-extension vscjava.vscode-maven
vscode --install-extension xabikos.JavaScriptSnippets
